source 'http://rubygems.org'

gem 'rails'
gem 'sqlite3'
gem 'inherited_resources'
gem 'devise'
gem 'rails_admin', :git => 'git://github.com/sferik/rails_admin.git'
gem 'yajl-ruby'
gem 'haml'
gem 'has_scope'
gem 'utilities'
gem 'kaminari'
